---
version: "2.3"
services:

  honeypot:
    build:
      context: .
      dockerfile: docker/Dockerfile2alpine
    image: honey:py2
    container_name: honeypot
    ports:
      - "19443:8443"
      - "19023:23"
    restart: unless-stopped